// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNBmI9qcqW0bErSLDm1ZApwXJ-izL8hcw',
    appId: '1:424333193955:web:eb3f49338fca72a01a4bd6',
    messagingSenderId: '424333193955',
    projectId: 'donttouchbell',
    authDomain: 'donttouchbell.firebaseapp.com',
    databaseURL: 'https://donttouchbell-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donttouchbell.firebasestorage.app',
    measurementId: 'G-VD71BS8QB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWh8LDscDuTrHAphuS_c27B5avcV6enrg',
    appId: '1:424333193955:android:8c588fb135ab56001a4bd6',
    messagingSenderId: '424333193955',
    projectId: 'donttouchbell',
    databaseURL: 'https://donttouchbell-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donttouchbell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5EFdOQGYWv64IgRKlYpoejX_SvKEAjuY',
    appId: '1:424333193955:ios:78fe95f646ff2a4d1a4bd6',
    messagingSenderId: '424333193955',
    projectId: 'donttouchbell',
    databaseURL: 'https://donttouchbell-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donttouchbell.firebasestorage.app',
    iosBundleId: 'kazuyukiikushima.b19.donttouchbell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5EFdOQGYWv64IgRKlYpoejX_SvKEAjuY',
    appId: '1:424333193955:ios:78fe95f646ff2a4d1a4bd6',
    messagingSenderId: '424333193955',
    projectId: 'donttouchbell',
    databaseURL: 'https://donttouchbell-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donttouchbell.firebasestorage.app',
    iosBundleId: 'kazuyukiikushima.b19.donttouchbell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNBmI9qcqW0bErSLDm1ZApwXJ-izL8hcw',
    appId: '1:424333193955:web:eb3f49338fca72a01a4bd6',
    messagingSenderId: '424333193955',
    projectId: 'donttouchbell',
    authDomain: 'donttouchbell.firebaseapp.com',
    databaseURL: 'https://donttouchbell-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donttouchbell.firebasestorage.app',
    measurementId: 'G-VD71BS8QB2',
  );
}