// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCHvYXdk_LCkgLPGSFVby_uLSKcBCmxg',
    appId: '1:540202646315:web:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '540202646315',
    projectId: 'shiritori-app-442a3',
    authDomain: 'shiritori-app-442a3.firebaseapp.com',
    storageBucket: 'shiritori-app-442a3.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1ION137BeHMwQDhLE4bNGUpACYrJJ3g',
    appId: '1:540202646315:android:64f88a16ee01a5c608a36e',
    messagingSenderId: '540202646315',
    projectId: 'shiritori-app-442a3',
    storageBucket: 'shiritori-app-442a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHCHvYXdk_LCkgLPGSFVby_uLSKcBCmxg',
    appId: '1:540202646315:ios:7edc944f1820c41b08a36e',
    messagingSenderId: '540202646315',
    projectId: 'shiritori-app-442a3',
    storageBucket: 'shiritori-app-442a3.firebasestorage.app',
    iosBundleId: 'co.jp.b19.atamaoshiriapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHCHvYXdk_LCkgLPGSFVby_uLSKcBCmxg',
    appId: '1:540202646315:ios:f19e34a8d0c64b7208a36e',
    messagingSenderId: '540202646315',
    projectId: 'shiritori-app-442a3',
    storageBucket: 'shiritori-app-442a3.firebasestorage.app',
    iosBundleId: 'com.example.shiritoriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHCHvYXdk_LCkgLPGSFVby_uLSKcBCmxg',
    appId: '1:540202646315:web:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '540202646315',
    projectId: 'shiritori-app-442a3',
    authDomain: 'shiritori-app-442a3.firebaseapp.com',
    storageBucket: 'shiritori-app-442a3.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}