// File generated by FlutterFire CLI.
// This is a template file. You need to create a Firebase project and run:
// flutter pub global activate flutterfire_cli
// flutterfire configure --project=your-project-id

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgwAof1kH0vh--PL6ga8EKwTpXfDxM7es',
    appId: '1:793591960853:web:d35be0c4b209badae5051c',
    messagingSenderId: '793591960853',
    projectId: 'kagami-yomi-online',
    authDomain: 'kagami-yomi-online.firebaseapp.com',
    storageBucket: 'kagami-yomi-online.firebasestorage.app',
    measurementId: 'G-KSKH0L8Q1T',
  );

  // TODO: Replace with your Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5GQGesmRpW2zOwefKjOVwTkAjjb8vtg',
    appId: '1:793591960853:android:b85b545f3a789b78e5051c',
    messagingSenderId: '793591960853',
    projectId: 'kagami-yomi-online',
    storageBucket: 'kagami-yomi-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAddEMNGFir8a0_9on2sZSI3dU3ilAP8',
    appId: '1:793591960853:ios:b87014201068fed3e5051c',
    messagingSenderId: '793591960853',
    projectId: 'kagami-yomi-online',
    storageBucket: 'kagami-yomi-online.firebasestorage.app',
    iosBundleId: 'com.beek.kagamiYomiOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAddEMNGFir8a0_9on2sZSI3dU3ilAP8',
    appId: '1:793591960853:ios:b87014201068fed3e5051c',
    messagingSenderId: '793591960853',
    projectId: 'kagami-yomi-online',
    storageBucket: 'kagami-yomi-online.firebasestorage.app',
    iosBundleId: 'com.beek.kagamiYomiOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgwAof1kH0vh--PL6ga8EKwTpXfDxM7es',
    appId: '1:793591960853:web:83ae733522821d12e5051c',
    messagingSenderId: '793591960853',
    projectId: 'kagami-yomi-online',
    authDomain: 'kagami-yomi-online.firebaseapp.com',
    storageBucket: 'kagami-yomi-online.firebasestorage.app',
    measurementId: 'G-P4QB05CJX6',
  );

}